### ISSUE TITLE
mechx interact throws error for agent 1

### ISSUE THREAD

**Issue by gabrielfior** [valory-xyz/mech-client#40]
Following the README, I tried fetching data from agent_id 1 on Gnosis
https://aimechs.autonolas.network/mech/0x3504fb5053ec12f748017248a395b4ed31739705/0x714ef7dafa358c7152f6703dd764a1df40d369dcf53275dd2543b0fdbf207298

however I get an error
```
:~/code/gnosis/mech-client-test$ mechx interact  "Tell me a joke" 1
Chain configuration: gnosis
Traceback (most recent call last):
  File "/home/gabrielfior/miniconda3/envs/mech-client/bin/mechx", line 8, in <module>
[...]
  File "/home/gabrielfior/miniconda3/envs/mech-client/lib/python3.10/site-packages/mech_client/interact.py", line 298, in verify_or_retrieve_tool
    available_tools = fetch_tools(
  File "/home/gabrielfior/miniconda3/envs/mech-client/lib/python3.10/site-packages/mech_client/interact.py", line 327, in fetch_tools
    return response["tools"]
KeyError: 'tools'
```

I debugged this a bit and found a possible cause - if you look at the agent definition for agent_id 6 ([link](https://gateway.autonolas.tech/ipfs/f01701220686ef29f7cead0d4d8b4960c231770c7ea55514f30a35e68e7dde04da3858677)), you see a `tools` key, whereas agent_id 1 doesn't have tools in its definition ([link](https://gateway.autonolas.tech/ipfs/f01701220714ef7dafa358c7152f6703dd764a1df40d369dcf53275dd2543b0fdbf207298)).

When I run the code above for agent_id 6, the prompt gets uploaded to IPFS (link below).

Relevant links:
-> Prompt generated for interaction with agent 6 - https://gateway.autonolas.tech/ipfs/f01701220a3901882dc60880c2e8538626f91f57125fdbbe44d6f6ec1c626801b82874512
-> Transaction created for fulfilling the request (failed because it ran out of gas) - https://gnosisscan.io/tx/0x465cddd037733073a1cb4c14abd9c54ac80695f970f53ffd5a47db9fa01a65ea

**Comment by gauravlochab** [comment]
correct the agent_id 1 doesn't have any tools, you can pass the agent_id(3 or 6 in this case) that has list of tools, thanks!

cc @0xArdi
