### ISSUE TITLE
Mech client hangs with `ConfirmationType.OFF_CHAIN`

### ISSUE THREAD

**Issue by evangriffiths** [valory-xyz/mech-client#42]
The `interact` method does not return with `confirmation_type == ConfirmationType.OFF_CHAIN`

In stdout I see
```
Created on-chain request with ID 56439741347897565096390923836077361339766652372962787639228859560995999907820
Waiting for Mech response...
```
but in the mech web UI [here](https://aimechs.autonolas.network/mech/0x77af31De935740567Cf4fF1986D04B2c964A786a) I can see that the request matching that ID has a corresponding response (i.e. an. IPFS link)

To reproduce:
```
from mech_client.interact import ConfirmationType, interact

private_key_path = "..."

def _interact(confirmation_type: ConfirmationType):
    interact(
        prompt="Is the sky blue?",
        # Taken from https://github.com/valory-xyz/mech?tab=readme-ov-file#examples-of-deployed-mechs
        agent_id=6,
        private_key_path=private_key_path,
        tool="prediction-offline",
        confirmation_type=confirmation_type,
    )


_interact(ConfirmationType.WAIT_FOR_BOTH)  # works fine
_interact(ConfirmationType.OFF_CHAIN)  # hangs
```

**Comment by gauravlochab** [comment]
@0xArdi i think the node uri-`acn.staging.autonolas.tech:9005` is not sending the response here  [response = await connection.receive()](https://github.com/valory-xyz/mech-client/blob/fe5b5ae50ab6bbb7979e75916ab25050bdd4d474/mech_client/acn.py#L166)

**Comment by KahanMajmudar** [comment]
This issue has been fixed in the latest release of the mech-client: 0.2.19
